### PR TITLE
re-add wrongly deleted styles in fba573f0c7e7c685a918c541238d759cc34f…

### PR DESCRIPTION
**Pull request by sahilakos**
@josh-padnick This should take care of the issues with wrongly deleted styles. I think something got messed up in my local that it overwrote so many styles on Nov 20. Should be fine now.

### CODE REVIEW

**Comment by brikis98** [comment]
What do these deleted styles do? Hard to tell from just looking at the code.

**Comment by josh-padnick** [comment]
> What do these deleted styles do?

It's a fair question. Most of these are optimizations I made to the checkout experience and Terms & Conditions. E.g. `code` makes the formatting of all source code look more appropriate for our site. 

Ideally, we'd clearly comment each of them, but honestly this is what was there before and I'm not sure the additional clarity is worth the commenting effort. My vote is to merge as is.

**Comment by brikis98** [comment]
No need to comment. It's just that usually, the styling changes go with functionality changes, so it's clearer what is being added/updated. In this case, they are standalone, so it's more confusing. I'm OK merging and releasing as-is.

**Comment by josh-padnick** [comment]
Oh, the context here is that [this commit](https://github.com/gruntwork-io/gruntwork-io.github.io/commit/fba573f0c7e7c685a918c541238d759cc34f00ec#diff-149baf93473d97ec899cef923e605e48) accidentally removed a bunch of styles and Sahil is restoring these. Great, I'll merge and deploy now!

**Pull request merged**
