### PR TITLE
Fix navbar margins

### PR DESCRIPTION
**Pull request by ina-stoyanova**
Screenshot 2021-08-19 at 16 12 40

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Hm, this creates a horizontal scrollbar for me:

Screen Shot 2021-08-19 at 2 17 40 PM

**Comment by ina-stoyanova** [comment]
Oh! What browser & version do you use?

**Comment by brikis98** [comment]
Chrome Version 92.0.4515.131 (Official Build) (arm64)

**Review by infraredgirl — APPROVED** [review]
Looks good!

**Comment by ina-stoyanova** [comment]
With the latest fix we've got this: 
Screenshot 2021-08-19 at 16 52 01 on all pages, except Patcher:
Screenshot 2021-08-19 at 16 53 57

I don't think it looks bad, but wanted to check with you. What's your thoughts on this, Jim?

**Review by brikis98 — APPROVED** [review]
LGTM!

**Pull request merged**
