### PR TITLE
Publish article on Migrating from Ref Arch 1.0 to 2.0

### PR DESCRIPTION
**Pull request by rhoboat**
The links will work once we publish this release: https://github.com/gruntwork-io/infrastructure-live-multi-account-acme/releases/tag/untagged-ea942753304ad7eb0824

### CODE REVIEW

**Review by bwhaley — DISMISSED** [review]
This LGTM!

**Comment by rhoboat** [comment]
Hm, I don't like these colors. The "tip" is red, but I'd rather it was the peaceful blue.

**Comment by rhoboat** [comment]
Should I make them this kind?

image

**Comment by bwhaley** [comment]
That's probably the easiest fix if you prefer it! I agree that the red is a bit jarring.

**Comment by ebeneliason** [comment]
> Should I make them this kind?
> 
> image

This looks good to me, and the icon layout looks cleaner as well. I think it's appropriate for the relatively mild level of severity the text conveys. That red is definitely aggressive, _especially_ given the vibrating contrast with the near-cyan blue in the text.

**Comment by rhoboat** [comment]
I was going to add some new styles to the `.admonitionblock` classes we have currently, to support `TIP` (like `.admonitionblock.tip` which is something Jekyll does support!), and I was going to add some new colors, like the muted green or yellow for tips. But I went with the blue. (We only currently have blue and red.)

image

Ready for another review @ebeneliason!

**Comment by rhoboat** [comment]
I noticed that the numbering here is wrong. It should increment:
image

**Comment by rhoboat** [comment]
This is annoying. If I try to "indent" the image, it turns into a code block and the image doesn't show up.

**Comment by rhoboat** [comment]
Ah, I got it working. Need to use single `:` rather than `::`.

**Review by bwhaley — APPROVED** [review]

**Comment by rhoboat** [comment]
Thanks for the review. I feel pretty good about it, and I know Eben has at least looked at it. Given that it's blocking all the downstream things we want to launch, I'm going to go ahead and merge this now.

**Pull request merged**
