### PR TITLE
Add Eben Eliason to the about page

### PR DESCRIPTION
**Pull request by ebeneliason**
@josh-padnick care to sanity check this when you have a chance?

### CODE REVIEW

**Comment by josh-padnick** [comment]
This looks great! Approving now so you can merge. Feel free to create a GitHub release so that it gets deployed to prod.

**Review by josh-padnick — APPROVED** [review]

**Comment by ebeneliason** [comment]
Happy to do the release, although I'm not familiar with the release workflow in GitHub so I may need some pointers. I found the draft release notes here, including some TODOs in the text: https://github.com/gruntwork-io/gruntwork-io.github.io/releases/edit/untagged-02d16955773c9fcbf552

Is there anything to it other than refining the release notes and pressing the green **Publish Release** button on that page? Is tagging manual?

**Comment by ebeneliason** [comment]
Oh, I'm now noticing the tag field in the edit view for the release notes, so that looks straightforward.

**Comment by josh-padnick** [comment]
It's mostly straightforward because of the [release notes drafter](https://github.com/gruntwork-io/prototypes/tree/master/release-notes-drafter), but you still have to edit the release notes manually to make sure they're formatted correctly. See https://github.com/gruntwork-io/gruntwork-io.github.io/releases/tag/v0.0.32 for the latest!

**Pull request merged**
