### PR TITLE
Update GCP Ref Arch Pricing

### PR DESCRIPTION
**Pull request by robmorgan**
This PR updates the GCP Ref Arch pricing to reflect its coming soon.

### CODE REVIEW

**Comment by robmorgan** [comment]
@josh-padnick feel free to tweak the 'Coming Soon. Contact Us.' text before you deploy.

**Comment by brikis98** [comment]
Watch out for https://github.com/gruntwork-io/gruntwork-io.github.io/pull/129

**Comment by brikis98** [comment]
(for context, #129 completely refactors the pricing page)

**Comment by oredavids** [comment]
Probably best if I rework this into #129

**Comment by robmorgan** [comment]
@oredavids thanks, that would be great 👍

**Comment by oredavids** [comment]
@robmorgan I have implemented this 👇🏼 in #129. Does it suffice so i can close this PR?

Screen Shot 2019-07-22 at 12 08 29 PM

**Comment by robmorgan** [comment]
@oredavids yep, closing!

**Pull request closed without merging**
