### PR TITLE
WWW-100

### PR DESCRIPTION
**Pull request by klijakub**
Hello Gruntwork team! 

1. ReCaptcha v3 is ready to use. 

2. I didn't change anything on your production FormBucket to avoid blocking any potential leads, if you want to test it on the gruntwork.io domain just copy google secret key from reCAPTCHA and paste it into FormBucket (image below) 
image

3. FormBucket API links are from your production bucket if you want to test it just switch to this commit -> [1d3b669](https://github.com/gruntwork-io/gruntwork-io.github.io/commit/1d3b66995a4dd149789f41be00a638af8f40a0ec)

4. Inside every new submission, Recaptcha token will appear at the bottom. I hope it's not a problem but we have to send it inside every contact POST request to verify the user.
image

5. I was working on our testing domain (altalab) you can remove it from your Recaptcha google acc when the task will be closed.

6. Gif showing request to formBucket with the token received from google reCAPTCHA request: 
Grunt

 
Please let me know if you have any problem to test it. 

Jira Item: [WWW-100]

[WWW-100]: https://gruntwork.atlassian.net/browse/WWW-100

### CODE REVIEW

**Comment by josh-padnick** [comment]
Thanks, @klijakub! @oredavids Could you test this out and take any final steps needed to launch it? This is non-urgent so perhaps finish out your current project before switching to this. Be sure to also assign the Jira ticket to yourself once you pick it up.

**Comment by josh-padnick** [comment]
@oredavids Per the above comment, could you take a look at this when your current work is completed?

**Comment by oredavids** [comment]
@josh-padnick yes I will.

**Comment by josh-padnick** [comment]
@oredavids Thanks! Given your review, let's deploy! What a relief to finally get less spam.

**Comment by josh-padnick** [comment]
Ah, I just read that you've already set the FormBucket keys, so I'll go ahead and deploy this now. I've re-enabled the Custom Recaptcha in FormBucket as well.

**Pull request merged**
