### PR TITLE
Mention Terraform Control Tower on Landing Zone page.

### PR DESCRIPTION
**Pull request by josh-padnick**
Before:
image

After:
image

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Hm, is this accurate? I thought:

* Landing Zone = IaC
* Control Tower = UI

**Comment by josh-padnick** [comment]
No, AWS Control Tower has replaced Landing Zone. In fact, you now customize Control Tower, albeit using a [nasty CloudFormation architecture](https://aws.amazon.com/solutions/implementations/customizations-for-aws-control-tower/). So I believe this is correct as is.

**Comment by brikis98** [comment]
Hm, not according to [this page](https://aws.amazon.com/controltower/faqs/):

> **How is AWS Control Tower different than the AWS Landing Zone solution?**
> Control Tower is an AWS native service providing a pre-defined set of blueprints and guardrails to help customers implement a landing zone for AWS accounts. AWS Landing Zone is an AWS solution offered through AWS Solution Architect, Professional Services, or AWS Partner Network (APN) Partners providing a fully configurable, customer-managed landing zone implementation. Customers can use either the Landing Zone solution or AWS Control Tower to create a foundational AWS environment based on best practice blueprints implemented through AWS Service Catalog. Control Tower is designed to provide an easy, self-service setup experience and an interactive user interface for ongoing governance with guardrails. While Control Tower automates creation of a new landing zone with pre-configured blueprints (e.g., AWS SSO for directory and access), the AWS Landing Zone solution provides a configurable setup of a landing zone with rich customization options through custom add-ons (e.g., Active Directory, Okta Directory) and ongoing modifications through a code deployment and configuration pipeline.
> 
> **When should I use AWS Landing Zone and when should I use AWS Control Tower?**
> You should use AWS Control Tower if you are looking for a self-service experience to set up an AWS environment based on a landing zone with pre-configured blueprints and then interactively govern your accounts with pre-configured guardrails. You will benefit from AWS Control Tower if you are building a new offering, have teams starting out on their journey to AWS, are starting a new cloud initiative, are completely new to AWS, or have an existing multi-account AWS environment. You should use the AWS Landing Zone solution if you are looking to set up a configurable landing zone with rich customization options through custom add-ons (e.g., Active Directory, Okta Directory) and change management through a code deployment and configuration pipeline.

**Comment by josh-padnick** [comment]
I actually think that page is out of date. In fact, I was recently speaking with someone who actively works at AWS and they told me that Control Tower is advised in all cases, in direct contradiction to that article. Also, Landing Zone is officially in "[long-term support](https://aws.amazon.com/solutions/implementations/aws-landing-zone/)", which is as close as AWS will get to deprecating anything.

**Review by brikis98 — APPROVED** [review]
Ah, alright then, good to know, thx!

**Pull request merged**
