### PR TITLE
Print styles for /terms/ & missing help text for Checkout

### PR DESCRIPTION
**Pull request by sahilakos**
No print button was added, but if you try and print the page you'll see print styles coming into play in your print preview.

### CODE REVIEW

**Comment by josh-padnick** [comment]
The print styles look great. I think removing the plain language text from the print is fine since anyone printing it won't need that in the printout anyway. Just one fix:

I noticed that the grayed out text isn't aligned with the non-grayed out text above it. For example:

image

Can you fix so that the left side of the text all starts against the same veritcal line?

**Comment by sahilakos** [comment]
Ah, I should have caught that. Will fix it.

Signup for our Monthly Love Newsletter <http://eepurl.com/cMOApP>, and
we'll send All Kinds Of Stories straight to your inbox. You'll love 'em.

--

Sahil Saini ("SAH-hil")
Founder + Digital Alchemist
(602) 550-3516 | Linkedin
<https://www.linkedin.com/in/sahil-saini-1166b032/>
w: akosweb.com

**Comment by sahilakos** [comment]
@josh-padnick @brikis98 

I added additional styles and adjustments for even smaller viewports (<= 320px, iPhone 5 & SEs).
- Fixed footer price is a bit smaller
- Right column checkout button is even smaller.
- Deposit Due Today is changed to Deposit Due only on <=320px viewports so it doesn't flow to second screen.

Additionally, View our TOS link was added right below Users Range Slider on XS screens. I tried to load up whole TOS in a modal, but it wasn't working because how much content there was. The mobile TOS link under users slider opens TOS in a new browser tab.

**Comment by sahilakos** [comment]
Oops!! Just did. I got to writing the comment before I pushed.


Signup for our Monthly Love Newsletter <http://eepurl.com/cMOApP>, and
we'll send All Kinds Of Stories straight to your inbox. You'll love 'em.

--

Sahil Saini ("SAH-hil")
Founder + Digital Alchemist
(602) 550-3516 | Linkedin
<https://www.linkedin.com/in/sahil-saini-1166b032/>
w: akosweb.com

**Comment by josh-padnick** [comment]
These changes look great! Just one final ask:

img_3409b41fefab-1

In the above screenshot, I completely missed the Terms of Service. Here's another idea for you could display it in mobile:

Using the same font as "Add-ons:", you add a header below "Reference Architecture" called "Legal:" and then put the "View our _Terms of Service_" link below that.

Once we resolve this, I think we're ready to launch.

**Comment by sahilakos** [comment]
Josh,

This is done and pushed.

Signup for our Monthly Love Newsletter <http://eepurl.com/cMOApP>, and
we'll send All Kinds Of Stories straight to your inbox. You'll love 'em.

--

Sahil Saini ("SAH-hil")
Founder + Digital Alchemist
(602) 550-3516 | Linkedin
<https://www.linkedin.com/in/sahil-saini-1166b032/>
w: akosweb.com

**Comment by josh-padnick** [comment]
Looks great now! Merging and pushing live.

**Pull request merged**
