### PR TITLE
Remove Etiene :(

### PR DESCRIPTION
**Pull request by brikis98**

### CODE REVIEW

**Comment by brikis98** [comment]
Merging given content. Feedback welcome!

**Comment by eak12913** [comment]
Have you already pushed these changes or do you need one of us to do it?

**Comment by brikis98** [comment]
Have not yet pushed. Feel free!

**Comment by eak12913** [comment]
Roger - I believe Zack's bio will also go out

**Comment by eak12913** [comment]
✅ - changes are now live.

**Comment by brikis98** [comment]
Thx!

**Pull request merged**
