### PR TITLE
Tweaks on heroku landing page 

### PR DESCRIPTION
**Pull request by ina-stoyanova**
- [x] Re-recorded gifs & uploaded to Imgur
- [x] Fixed borders around each step on the homepage

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR!

One note: we are currently showing these on the landing page at a resolution of 415x293. The gifs on imgur are larger than that, so the browser will resize them, making them blurry. Usually, if you resize it with proper software, it's much more effective than letting the browser do it. Could you give that a shot?

**Comment by ina-stoyanova** [comment]
> Thanks for the PR!
> 
> One note: we are currently showing these on the landing page at a resolution of 415x293. The gifs on imgur are larger than that, so the browser will resize them, making them blurry. Usually, if you resize it with proper software, it's much more effective than letting the browser do it. Could you give that a shot?

I actually did resize them using proper software, but kept the original resolution, which was 850x600. I will reduce them in dimensions too now.

**Comment by ina-stoyanova** [comment]
Okay, after playing around with a few different tools, I'll have to re-record these. Whatever size I reduce them to, they still come up very blurry. And the compression removes extra frames in between, so it looks even worse.

**Review by brikis98 — APPROVED** [review]
LGTM!

**Comment by ina-stoyanova** [comment]
Thanks for the review! Will merge and release now!

**Comment by brikis98** [comment]
Don't forget to do a new release to deploy these changes!

**Pull request merged**
