### PR TITLE
Add first batch of re-cut images

### LINKED ISSUE #619: Blurry images in Patcher How it Works page
A few of the images on the [Patcher How it Works page](https://gruntwork.io/patcher/how-it-works) are blurry:

1. Update the code for your library
1. Merge and release
1. Patcher auto discovers your dependencies
1. Patcher patches your code and opens a PR
1. You review and merge

See [here](https://www.joelonsoftware.com/2002/02/13/the-iceberg-secret-revealed/) for why blurry images are a problem. See [here](https://gruntwork.atlassian.net/browse/WWW-124?focusedCommentId=13843) for ideas for how to improve the images. See also https://github.com/gruntwork-io/gruntwork-io.github.io/issues/616 for a related issue.

### PR DESCRIPTION
**Pull request by zackproser**
Fixes #619

### CODE REVIEW

**Comment by zackproser** [comment]
I've not yet been able to export the Patcher auto discovers your dependencies image at a resolution that makes the rendered image crisper.

**Review by brikis98 — COMMENTED** [review]
On my screen, both of these images look a little better, but are still blurry. Example:

Screen Shot 2021-08-24 at 1 12 14 PM

In Chrome dev tools, if you mouse over the image, it shows both the rendered size and intrinsic size, and I think you're still off by a few pixels, so the browser is still resizing the image, and the result is blurry:

Screen Shot 2021-08-24 at 1 13 18 PM

**Comment by brikis98** [comment]
> I've not yet been able to export the Patcher auto discovers your dependencies image at a resolution that makes the rendered image crisper.

Is there a figma image of this or something we're using as the source?

**Comment by zackproser** [comment]
> > I've not yet been able to export the Patcher auto discovers your dependencies image at a resolution that makes the rendered image crisper.
> 
> Is there a figma image of this or something we're using as the source?

Yes, we're using [this figma board](https://www.figma.com/file/grdjL3p0lpsAua2NkEa67v/Gruntwork-Developer-Portal-(Copy)?node-id=6856%3A55112), which is a copy. The target node is "Team Remove (Alt)".

**Comment by brikis98** [comment]
> > > I've not yet been able to export the Patcher auto discovers your dependencies image at a resolution that makes the rendered image crisper.
> > 
> > 
> > Is there a figma image of this or something we're using as the source?
> 
> Yes, we're using [this figma board](https://www.figma.com/file/grdjL3p0lpsAua2NkEa67v/Gruntwork-Developer-Portal-(Copy)?node-id=6856%3A55112), which is a copy. The target node is "Team Remove (Alt)".

Thanks!

BTW, if the [idea here works](https://github.com/gruntwork-io/gruntwork-io.github.io/pull/622#pullrequestreview-737205251), we could use it on the How it Works page for the same `.gif`!

**Comment by zackproser** [comment]
Okay, I've re-cut all the offending images at exactly 410px by 310px. It appears to improve things markedly in full-screen where the image is not resized. I still see improvement but some remaining bluriness when the page is sized down to half-screen or below.

**Review by brikis98 — APPROVED** [review]
LGTM, thanks Zack!

**Comment by brikis98** [comment]
Merging now.

**Pull request merged**
