### PR TITLE
Add Ian Bowers

### PR DESCRIPTION
**Pull request by iangrunt**
Adding myself to Team page

### CODE REVIEW

**Comment by josh-padnick** [comment]
LGTM, but the one feedback is that your profile pic is a touch blurry. Do you have anything higher res? If not, no worries.

**Comment by iangrunt** [comment]
> LGTM, but the one feedback is that your profile pic is a touch blurry. Do you have anything higher res? If not, no worries.

That's good feedback, I'll see if I can get one today!

**Comment by josh-padnick** [comment]
Roger!

**Comment by josh-padnick** [comment]
Hey Ian, I think we should merge this as is and if you find a higher-res photo later on, we can add it then. But best not to have long-running PRs sit open for a while.

**Review by josh-padnick — APPROVED** [review]

**Pull request merged**
