### PR TITLE
Upgrade to Jekyll 4.1.0

### PR DESCRIPTION
**Pull request by josh-padnick**
In the absence of automatically previewable PRs, I've been running branches on my local machine, and found Jekyll frustratingly slow to load changes. This PR updates to Jekyll 4.1.0 in an effort to speed things up.

The initial build seems about the same, but the live reload builds seem about 50% faster, which is a nice savings of 2 seconds. This can probably be tweaked further and may risk breaking something, but I won't have additional time to check on that.

Feedback welcome on whether the risks are worth the benefits here.

**Update:** Note that I have not reviewed the [Jekyll 3.x to 4.x Upgrade Instructions](https://jekyllrb.com/docs/upgrading/3-to-4/). There may be important considerations there.

### CODE REVIEW

**Comment by josh-padnick** [comment]
@eak12913 @oredavids Any issue merging this? Any suggestions on how we test if Jekyll 4.0.0 is going to render the site differently somehow?

**Comment by josh-padnick** [comment]
Thanks, @eak12913! Merging and deploying now.

**Comment by josh-padnick** [comment]
@eak12913 Looks like the [CircleCI build failed](https://app.circleci.com/pipelines/github/gruntwork-io/gruntwork-io.github.io/84/workflows/3b7b24bd-0533-41b7-a0a7-2ae70aaded92/jobs/66/parallel-runs/0/steps/0-107) due to an s3_website issue. Can you investigate?

**Comment by eak12913** [comment]
Hey @josh-padnick, you are correct. There was indeed an issue that I introduced here. I have already resolved this issue with #316 

CI/CD is now restored and I've deployed prod to make sure it has all the changes you were trying to deploy.

**Comment by josh-padnick** [comment]
Thanks for the prompt response!

**Pull request merged**
