### PR TITLE
Add Map to About Page

### PR DESCRIPTION
**Pull request by sahilakos**
Hey @josh-padnick, here's how the map looks: https://cl.ly/30a7258f075f. Let me know if there's any changes you'd like made to it. We left off the team member names intentionally, let me know if you'd like for us to add those to markers too.

### CODE REVIEW

**Comment by josh-padnick** [comment]
Ok, this is completely bad-ass. Well done on this! Some thoughts:

- It's a little odd that we have more markers than Grunts above. For that reason, can your team take the lead on [adding Bijou](https://3.basecamp.com/3989840/buckets/9063434/todos/1313506460) and [adding Monica](https://3.basecamp.com/3989840/buckets/9063434/todos/1313507017) to the website as part of this PR?

- There are a bunch of deletions here (317 lines to be exact) that look important. Are you sure your code is pulling the latest commit from the official repo `master`?

Otherwise, this looks great and I'm excited to launch it.

**Comment by sahilakos** [comment]
Will do @josh-padnick, I didn't see the deletions part. That's odd. We'll double check on our end.

For new team members, the links you posted don't work for me. Can you add me to those tasks in Basecamp.

**Comment by josh-padnick** [comment]
@sahilakos Just granted you access to the Basecamp links. Please try again now. Sounds good on other items. Thanks for the prompt response!

**Comment by brikis98** [comment]
Love it. This looks awesome! 

What's the reason to leave off the names? For privacy reasons? Isn't that info available on LinkedIn/Twitter usually anyway?

**Comment by josh-padnick** [comment]
Hey Sahil, thanks for checking on this. I think it's better to leave the names off the map. Yes, that's available on LinkedIn, but at least individuals can control that there. So, I think we're good to go here! I'll merge and deploy now.

**Comment by josh-padnick** [comment]
Ok, I added our two newest hires and renamed the file something slightly more intuitive. Now merging and deploying.

**Pull request merged**
