### PR TITLE
Unify the copy on the how-it-works page with homepage

### LINKED ISSUE #615: Inconsistent text in Patcher pages
There are two sets of text in the Patcher page that are similar, but not the same, and in some ways, contradictory:

1. On the home page, the core zig-zag says things like: 
    1. Install the Patcher App. Get Patcher up and running with just a few clicks. Start completely for free. You can find the app in GitHub, BitBucket or GitLab.
    1. Patcher discovers your dependencies automatically. Patcher discovers dependencies for popular languages and tools such as JavaScript, Ruby, Java, Python, Go, Terraform, and Docker. You can also add special comments to your code to help Patcher discover dependencies in non-standard locations (e.g., in a Bash script).
2. On the [How it Works page](https://www.gruntwork.io/patcher/how-it-works), in the User Flow, the zig-zag says things like: 
    1. Install Patcher. It's a GitHub App.
    1. Patcher auto discovers your dependencies. It does this automatically. You can also help it along with manual hints.

We should be consistent in both places! I think the home page version is more accurate, so we should probably use that as the source of truth.

### PR DESCRIPTION
**Pull request by zackproser**
Closes #615

### CODE REVIEW

**Review by bwhaley — APPROVED** [review]
LGTM

**Review by brikis98 — COMMENTED** [review]
Thanks Zack.

I think the other steps below these two need to be synced up too.

**Comment by zackproser** [comment]
> Thanks Zack.
> 
> I think the other steps below these two need to be synced up too.

To ensure I understand, you want the remaining steps from the homepage: 

- "Maintainers release new versions and patches" 
- "Patcher automatically patches your code and opens a pull request"
- "You review and merge" 

and their body text to replace the current steps on the user tab of the how-it-works page: 

- "Patcher patches your code and opens a PR" 
- "You review and merge"

**Comment by brikis98** [comment]
> > Thanks Zack.
> > I think the other steps below these two need to be synced up too.
> 
> To ensure I understand, you want the remaining steps from the homepage:
> 
> * "Maintainers release new versions and patches"
> * "Patcher automatically patches your code and opens a pull request"
> * "You review and merge"
> 
> and their body text to replace the current steps on the user tab of the how-it-works page:
> 
> * "Patcher patches your code and opens a PR"
> * "You review and merge"

Ah, sorry for the confusion. I meant to sync up the last two steps from the home page with the corresponding last two steps on the how it works page. I think those are supposed to be the same, right?

**Comment by zackproser** [comment]
> > > Thanks Zack.
> > > I think the other steps below these two need to be synced up too.
> > 
> > 
> > To ensure I understand, you want the remaining steps from the homepage:
> > 
> > * "Maintainers release new versions and patches"
> > * "Patcher automatically patches your code and opens a pull request"
> > * "You review and merge"
> > 
> > and their body text to replace the current steps on the user tab of the how-it-works page:
> > 
> > * "Patcher patches your code and opens a PR"
> > * "You review and merge"
> 
> Ah, sorry for the confusion. I meant to sync up the last two steps from the home page with the corresponding last two steps on the how it works page. I think those are supposed to be the same, right?

Roger - done in 2138213d

**Review by brikis98 — APPROVED** [review]
Thanks! 👍

**Comment by zackproser** [comment]
Thanks for the reviews! Going to merge this in now.

**Pull request merged**
