### PR TITLE
Increase span callout font size

### PR DESCRIPTION
**Pull request by hngerebara**
Increase span callout font size

### CODE REVIEW

**Comment by brikis98** [comment]
Could you share a before/after screenshot?

**Comment by hngerebara** [comment]
**Before:** 
Screenshot 2019-09-19 at 10 30 17 AM

**After**
Screenshot 2019-09-19 at 10 30 01 AM

**Comment by brikis98** [comment]
Looks a bit odd to have the code text bigger than the rest. Perhaps increase the font size for all the text in call outs to be the same (i.e., slightly larger than it was originally)?

**Comment by Etiene** [comment]
The before one looks correct and better than the 14px one. But I clearly remember Jim finding one instance of this where the span was smaller than the rest. Was this something that's working differently on some screens? Was the problem one particular span? 

> Perhaps increase the font size for all the text in call outs to be the same (i.e., slightly larger than it was originally)? 

I don't think this is a solution to the original problem

**Comment by brikis98** [comment]
> I don't think this is a solution to the original problem

Why not? The font is pretty small for callouts, so making it bigger doesn't seem to hurt... And would also make the font bigger for code spans within callouts.

**Comment by Etiene** [comment]
Because the problem is here
Screen Shot 2019-09-19 at 11 03 11

**Comment by brikis98** [comment]
Oh, yea, that's even better to fix 👍

**Comment by hngerebara** [comment]
It still doesn't make any difference. Unless I'll change the entire font

**Comment by hngerebara** [comment]
This has now been fixed. Had a sync with @Etiene to be certain
Screenshot 2019-09-19 at 12 45 24 PM

**Pull request merged**
