### PR TITLE
Add Gruntwork Store to footer

### PR DESCRIPTION
**Pull request by brikis98**
Same as https://github.com/gruntwork-io/mission-control/pull/308.

### CODE REVIEW

**Comment by josh-padnick** [comment]
LGTM! Not sure if it should say "Gruntwork Store" or "Buy Gruntwork Swag" but I don't feel strongly either way.

**Comment by brikis98** [comment]
Thanks for the reviews! Both PRs are now approved, so I'll merge them. @eak12913 When you get a chance, could you deploy this one? Thanks!

**Comment by eak12913** [comment]
Deployed!

**Comment by brikis98** [comment]
Thank you!

**Pull request merged**
