### PR TITLE
[APT-1542] Remove Houston page, references and links

### PR DESCRIPTION
**Pull request by oredavids**
[APT-1542]

[APT-1542]: https://gruntwork.atlassian.net/browse/APT-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Note: We'll need to remove https://blog.gruntwork.io/authenticating-to-aws-with-gruntwork-houston-2167e85a402b and the references in the rest of that series to it as well!

**Comment by josh-padnick** [comment]
@brikis98 All blog posts are updated to remove reference to Houston, however as far as we can tell, the story author must delete / archive the story. We don't seem to have an option to do it. Can you try that out?

https://blog.gruntwork.io/authenticating-to-aws-with-gruntwork-houston-2167e85a402b

**Review by ebeneliason — APPROVED** [review]
LGTM

**Comment by brikis98** [comment]
Story deleted!

**Pull request merged**
