### PR TITLE
Add link to refarch blog post

### PR DESCRIPTION
**Pull request by yorinasub17**
This adds a link to the new ref arch blog post in our ref arch product page. Let me know if you imagined the link should live somewhere else!

### CODE REVIEW

**Comment by yorinasub17** [comment]
> You could also add a link in the "What's Included" section further down.
Done: b06448

**Comment by yorinasub17** [comment]
Merging and deploying. Thanks for review!

**Comment by brikis98** [comment]
@yorinasub17 Sorry, just realized one more place we should add this: https://gruntwork.io/devops-resources/

**Comment by yorinasub17** [comment]
Saw that you got to it. Thanks for taking care of that!

**Pull request merged**
