### PR TITLE
Updates images from Patcher Landing Page

### LINKED ISSUE #609: Replace images on Patcher landing page with less blurry ones
1. The ["Use the UI" image](https://gruntwork.io/patcher#patcher-discovers-your-dependencies-automatically) is great, but blurry. We probably need a `.gif` of scrolling through it.
2. The ["Use the CLI" `.gif`](https://gruntwork.io/patcher#patcher-discovers-your-dependencies-automatically) is also great, but again, blurry and hard to see. We should probably re-record with something like https://asciinema.org/.
3. The [example pull request image](https://gruntwork.io/patcher#patcher-automatically-patches-your-code-and-opens-a-pull-request) should probably be replaced with the sharper one [added here](assets/img/logos-patcher/patch-rails-vulnerability.png).
4. The ["You review and merge"](https://gruntwork.io/patcher#you-review-and-merge) image also needs to be a bit more crisp.

See [here](https://gruntwork.atlassian.net/browse/WWW-124?focusedCommentId=13843) for thoughts on how to improve images.

### PR DESCRIPTION
**Pull request by marinalimeira**
Closes #609 

- [x] The ["Use the UI" image](https://gruntwork.io/patcher#patcher-discovers-your-dependencies-automatically) is great, but blurry. We probably need a `.gif` of scrolling through it.
- [x] The ["Use the CLI" `.gif`](https://gruntwork.io/patcher#patcher-discovers-your-dependencies-automatically) is also great, but again, blurry and hard to see. We should probably re-record with something like https://asciinema.org/.
- [x] The [example pull request image](https://gruntwork.io/patcher#patcher-automatically-patches-your-code-and-opens-a-pull-request) should probably be replaced with the sharper one [added here](assets/img/logos-patcher/patch-rails-vulnerability.png).
- [x] The ["You review and merge"](https://gruntwork.io/patcher#you-review-and-merge) image also needs to be a bit more crisp.

### CODE REVIEW

**Comment by marinalimeira** [comment]
I updated the UI with the feedbacks from [here](https://github.com/gruntwork-io/gruntwork-io.github.io/pull/584#issuecomment-901728960). Feedbacks before recording the gif?

Screen Shot 2021-08-20 at 16 11 29

**Comment by marinalimeira** [comment]
> The "You review and merge" image also needs to be a bit more crisp.

What "more crisp" means in this context?

**Comment by brikis98** [comment]
> I updated the UI with the feedbacks from [here](https://github.com/gruntwork-io/gruntwork-io.github.io/pull/584#issuecomment-901728960). Feedbacks before recording the gif?
> 
> Screen Shot 2021-08-20 at 16 11 29

Nice!

Minor tweaks to consider:

1. There are two status columns. Perhaps name the second one "actions"?
2. The phrasing "Open PR #XXX" sounds like by clicking it, you would open a new PR. However, here, the PR is already open, so perhaps the text should be "Updating in PR #XXX".
3. For the rows that are already up to date, perhaps the last column should have the link, "Roll back".
4. The first column heading should probably be singular: "Dependency" instead of "Dependencies."

**Comment by brikis98** [comment]
> > The "You review and merge" image also needs to be a bit more crisp.
> 
> What "more crisp" means in this context?

More crisp means "more sharp" or "less blurry."

**Review by hposca — APPROVED** [review]
:+1:

**Comment by zackproser** [comment]
Thanks for reviewing! Going to merge this in now.

**Pull request merged**
