### PR TITLE
[WWW-93] Landing zone page

### PR DESCRIPTION
**Pull request by klijakub**
Hello,
- landing zone for aws subpage is ready
- added new assets from the approved design

Jira Item: [WWW-93]
[WWW-93]: https://gruntwork.atlassian.net/browse/WWW-93

### CODE REVIEW

**Comment by josh-padnick** [comment]
This is now ready to merge! @oredavids @eak12913 Could you approve and merge this as non-contributor?

**Review by eak12913 — DISMISSED** [review]
Rubber stamping!

**Review by eak12913 — COMMENTED** [review]
Folks - I'm unable to merge this because it's out of date with the base branch.

**Comment by klijakub** [comment]
@eak12913 please check now, I've updated ;)

**Comment by eak12913** [comment]
@klijakub - Thank you. I'm keeping an eye on this. Our internal script is having a tough time at the moment and I'm actually unable to merge this PR until that script completes. As soon as we resolve the issue we will merge!

**Comment by eak12913** [comment]
@klijakub one more favor - can you push some test/nothing commit to this branch and then push something else to undo it...ie - put "test" into a README...and then revert that. We can try to use this to re-trigger the "non-contributor" approval script that's failing to run here

**Review by eak12913 — APPROVED** [review]
Rubber stamping so we can merge

**Comment by eak12913** [comment]
@klijakub Thank you. Merged!

**Pull request merged**
