### PR TITLE
Fix screen resolution

### PR DESCRIPTION
**Pull request by hngerebara**
Fix different screen sizes

**To Test:**

Check view on different screen sizes

### CODE REVIEW

**Comment by Etiene** [comment]
I think this PR contains some commits that are not supposed to be here?

**Comment by hngerebara** [comment]
Yes sorry, I've changed the base. It was checked out from the resize-thumbnails branch

**Comment by Etiene** [comment]
Ok, the code looks good to me, but I can't tell what changed, everything looks fine on my screen and on the screens I tried on browserstack. Could you post some before x after screenshots for the screens you fixed?

**Comment by hngerebara** [comment]
**Before:**
Screenshot 2019-09-16 at 2 43 40 PM

**After**
Screenshot 2019-09-16 at 2 44 29 PM

**Before**
Screenshot 2019-09-16 at 2 45 41 PM

**After**
Screenshot 2019-09-16 at 2 46 35 PM

**Comment by brikis98** [comment]
What's the status on this PR?

**Comment by Etiene** [comment]
Approved, but needs fixing conflict with master before merging.

**Comment by Etiene** [comment]
I'll rebase this one

**Comment by Etiene** [comment]
wow, the conflicts on this one were hard to solve! 

I ended up adding some other fixes then:

Removed the search and filters (all the tags were looking awful on mobile and rather than fix it, I think we should just hide it until we do a full pass on what should be our final mobile design)  and corrected the cloud filters size.

Screen Shot 2019-09-17 at 18 05 03

**Comment by hngerebara** [comment]
Thanks, Etienne. We were more focused on tablets and above not mobile devices. But I think it's nice you took off the parts looking awful on mobile device view so it still looks good. 

LGTM

**Pull request merged**
