### PR TITLE
[CORE-1248] Update terms-of-service.yml

### PR DESCRIPTION
**Pull request by ebeneliason**
Update 9.8 Service Data section to use standard language.

### CODE REVIEW

**Review by josh-padnick — DISMISSED** [review]
LGTM!

**Comment by ebeneliason** [comment]
@josh-padnick If you have a chance to re-review this I can push it through. For context, I realized that our plain speak was no longer aligned with the legalese, given that we now collect non-anonymous data. In addition to this change, the proposed revised text for the legal feed is:

> We updated this section to use familiar contract language regarding the collection of both anonymous and identifiable customer data necessary to operate the business and improve our products and services.

**Comment by josh-padnick** [comment]
I'm concerned about removing this line:

> To the extent such Service Data is considered Personal Data under Applicable Data Protection Law, Gruntwork shall be responsible for and shall process such data in accordance with the Gruntwork Privacy Policy and Applicable Data Protection Law.

Does this materially "reduce" our commitment to data privacy? If not, no worries, and let's merge as is. If so, let's figure out how to keep that commitment on par with updated language. Please check with JB to get these answers.

**Comment by josh-padnick** [comment]
Proposed re-word:


@josh-padnick If you have a chance to re-review this I can push it through. For context, I realized that our plain speak was no longer aligned with the legalese, given that we now collect non-anonymous data. In addition to this change, the proposed revised text for the legal feed is:

_We adopted more conventional contract language regarding the collection of both anonymous and identifiable customer data that we'll use to operate the business and improve our products and services._

**Comment by ebeneliason** [comment]
> Does this materially "reduce" our commitment to data privacy? If not, no worries, and let's merge as is. If so, let's figure out how to keep that commitment on par with updated language. Please check with JB to get these answers.

Per JB, "Section 9.3 and 9.4 cover our bases with respect to our use and protection of Personal Data." I think this is ready for merge. Once merged, I'll open a PR for the legal feed update with the revised phrasing above.

**Review by MoonMoon1919 — APPROVED** [review]

**Pull request merged**
