### PR TITLE
Adding Patcher How it Works page

### LINKED ISSUE #541: Create separate "How it Works" page for Patcher
Go into a bit more detail of how maintainers create Patches and how Patcher executes those. [See show, don't tell here](https://www.notion.so/gruntwork/Patcher-backwards-incompatible-internal-dependency-workflows-2e260347cd6a470384c998e22a0c1895#1b890fd631044390b896f5509e242b92).

One thing to consider for this page is two views: an "end user" view and a "maintainer" view. Each view (tab?) shows the experience for that party. E.g., The End user installs a GitHub app, gets PRs with updates, reviews the code, sees tests run, and merges. The maintainer updates their code, creates a patch, tests the patch with a `patcher` CLI, and then creates a new release in GitHub.

**Update**: I flushed this idea out more [below](https://github.com/gruntwork-io/gruntwork-io.github.io/issues/541#issuecomment-896131059).

### PR DESCRIPTION
**Pull request by robmorgan**
Closes #541.

Preview: https://deploy-preview-557--keen-clarke-470db9.netlify.app/patcher/how-it-works/

Screen Shot 2021-08-12 at 4 36 18 pm

### CODE REVIEW

**Comment by ina-stoyanova** [comment]
Hey Rob, is this ready for review?

**Comment by ina-stoyanova** [comment]
OK, so after reviewing this PR, there's still these outstanding tasks:
- [ ] align content as much as needed between the page and how-it-works section 
- [ ] update images - that's currently in progress with @marinalimeira 
- [ ] fix link from navbar to point to page, not section. Do we want to link to the section too? I guess not, or we could rename the page to avoid the conflict in names. 
- [ ] review content & remove references to Hipaa

**Review by hposca — APPROVED** [review]
:+1:

**Comment by zackproser** [comment]
Thanks for reviewing! Going to merge this in now.

**Pull request merged**
