### PR TITLE
Add Houston landing page

### PR DESCRIPTION
**Pull request by brikis98**
This PR adds a simple landing page for Houston so we can announce it in our newsletter and start seeing how people respond. I've included several recorded videos of various Houston features. It's not perfect, but hopefully captures the basic idea.

Here's a .gif I captured of scrolling through the page:

houston-splash-page

### CODE REVIEW

**Comment by mcalhoun** [comment]
It scrolled by kind of quick...but do we have a call to action? Like "Request Beta Access" or similar?

**Comment by brikis98** [comment]
Yea, two places: one in the middle of the page (under "Gruntwork Houston Beta") and one at the bottom ("Sign up for the Gruntwork Houston beta!").

**Comment by mcalhoun** [comment]
Oh...I see it now....LGTM! 👍

**Comment by brikis98** [comment]
BTW, I've added most of the same gifs to this month's newsletter if you want a preview: https://medium.com/p/7354835132f8/edit

**Comment by brikis98** [comment]
On second thought, perhaps it's time to just put all of that in it's own blog post...

**Comment by brikis98** [comment]
OK, converted into a full blog post here: https://medium.com/p/3a4603852db1/edit

**Comment by brikis98** [comment]
Deploying now.

**Pull request merged**
