### PR TITLE
add ga tracking on click

### PR DESCRIPTION
**Pull request by hngerebara**
Add GA tracking to guides
- Breadcrumb
- Categories on listing page
- Guides listing
Screenshot 2019-10-02 at 11 38 19 AM

### CODE REVIEW

**Comment by brikis98** [comment]
I think the tracking we want is for the links within the guides _to other pages_. GA already tracks URLs and clicks _within_ the website, so the main goal is to figure out what users are clicking on while reading the guides: e.g., do the click our CTAs to subscribe or view training?

**Comment by hngerebara** [comment]
I noticed our CTA's to subscribe redirects the customer to the homepage. I guess we want this to be linked to our contact us page?. 
GA already tracks Outbound links so there won't be any ned tracking it

**Comment by brikis98** [comment]
You're right, this task isn't specified well enough. We actually have several CTAs on each guide:

1. "You must be a subscriber to view the code." This should pop up a [subscribe modal](https://projects.invisionapp.com/d/main#/console/17881048/380601682/preview). It occurs to me we never implemented that! Could you file a Jira ticket to think about how we could do that? Perhaps the best approach is for those upsells to all link to `gruntwork.io/pricing` and for the guides page to capture those clicks and show the upsell modal (and track the click!).
1. Links to our training videos at `training.gruntwork.io`. We could probably leave these as-is and track clicks to `training.gruntwork.io`... 
1. The "Have Gruntwork deploy this for me" CTA. This is a WIP in another Jira card. If we implement our own modal, we'll want tracking in it. If we go with Intercom, it's worth digging into whether we can track that.

**Comment by hngerebara** [comment]
Currently working on the subscribe [modal](https://github.com/gruntwork-io/gruntwork-io.github.io/pull/205) so I can implement ga tracking on it

**Comment by hngerebara** [comment]
Rather than closing out this PR, I feel it can still be used to know if people actually click on any of these. Can help us answer minor questions like. Do people really click the breadcrumb or categories? are they really useful?

**Pull request merged**
