### PR TITLE
Eks enterprise fixes

### PR DESCRIPTION
**Pull request by yorinasub17**
- https://gruntwork.atlassian.net/browse/WWW-125 (c29ff8a)
- https://gruntwork.atlassian.net/browse/WWW-126 (d7e8005)
- https://gruntwork.atlassian.net/browse/WWW-127 (0afce74)

### CODE REVIEW

**Comment by josh-padnick** [comment]
Thanks, Yori!

## WWW-125

Looks good!

## WWW-126

I'm not sure how usable this is:

image

I realize it would make the contact us form longer, but can you try stacking the checkboxes vertically to see if that improves readability?

## WWW-127

Looks good!

**Comment by yorinasub17** [comment]
> I realize it would make the contact us form longer, but can you try stacking the checkboxes vertically to see if that improves readability?

Done: 
64061a7

**Review by josh-padnick — APPROVED** [review]
LGTM!

**Comment by yorinasub17** [comment]
Thanks for review! Merging.

**Comment by brikis98** [comment]
> ## WWW-126
> I'm not sure how usable this is:
> 
> image
> 
> I realize it would make the contact us form longer, but can you try stacking the checkboxes vertically to see if that improves readability?

Hm, I think the design I had in the [original ticket](https://gruntwork.atlassian.net/browse/WWW-126) was a bit different:

Screen Shot 2021-08-10 at 9 51 20 AM

Notes:

1. No "Which features are you interested in?" We just go straight into the options.
2. Each option fits on one row. I did that work in the browser, so I'm confident you can make those fit.

I think that had the best combination of readability and not making the form too long.

**Comment by josh-padnick** [comment]
Jim, I asked Yori to make it vertical since I found it longer to scroll but easier to fill out. I actually still think that's the case and prefer what's currently there. That being said, why don't you make the final call here so we're not giving conflicting directives.

**Comment by yorinasub17** [comment]
> Each option fits on one row. I did that work in the browser, so I'm confident you can make those fit.

Can you give me some pointers here on how you did that? No matter how I organize the grid, I can't get it as clean as you have it. Did you use bootstrap rows to do this? Or HTML tables in the row? Or raw padding and margins?

**Comment by brikis98** [comment]
> Jim, I asked Yori to make it vertical since I found it longer to scroll but easier to fill out. I actually still think that's the case and prefer what's currently there. That being said, why don't you make the final call here so we're not giving conflicting directives.

I don't think it's a huge issue, but I find the long vertical page intimidating, and worry many customers will just bounce rather than filling that out. My guess is the horizontal layout is just as easy to understand, but less scary, in the sense that you can see the end of the page, rather than getting the impression that it's an endless form.

> > Each option fits on one row. I did that work in the browser, so I'm confident you can make those fit.
> 
> Can you give me some pointers here on how you did that? No matter how I organize the grid, I can't get it as clean as you have it. Did you use bootstrap rows to do this? Or HTML tables in the row? Or raw padding and margins?

That's my bad, I should've saved/shared the code when I was messing with it in dev tools. At this point, I don't entirely remember. I _think_ what I did was add `float: left` on the `div` that wraps each checkbox/label. I then set `width` on those `div` so that they were spaced out as equal sized columns: e.g., the first `div` in each row had `width: 120px`, the second div had `width: 160px`, etc. And I arranged the choices so that the shorter options went in narrower columns, longer options in wider ones, etc. It's ugly, but seemed to work. Oh, I also removed the top padding on the `label` for each row (e.g., Service Mesh, Self-service Dashboard) so it aligned better. I just repro'd it for a couple rows quickly in web tools and copy/pasted it out (the `style=` are the key changes):

```html
<div class="form-group">
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <label style="padding-top: 0;">Service Mesh</label>
    </div>
    <div class="col-xs-12 col-md-8">
      <div style="float: left; width: 120px;">
        <input id="istio" name="interested-feature-service-mesh" type="checkbox" value="Istio">
        <label for="istio">Istio</label>
      </div>
      <div style="float: left; width: 160px;">
        <input id="consul-connect" name="interested-feature-service-mesh" type="checkbox" value="Consul Connect">
        <label for="consul-connect">Consul Connect</label>
      </div>
      <div style="float: left; width: 160px">
        <input id="aws-app-mesh" name="interested-feature-service-mesh" type="checkbox" value="AWS App Mesh">
        <label for="aws-app-mesh">AWS App Mesh</label>
      </div>
    </div>
  </div>
</div>
```

**Comment by yorinasub17** [comment]
Thanks for the pointer. This is now done in https://github.com/gruntwork-io/gruntwork-io.github.io/pull/598

**Pull request merged**
