### PR TITLE
Fix typo in CICD guide

### PR DESCRIPTION
**Pull request by yorinasub17**

### CODE REVIEW

**Comment by brikis98** [comment]
@eak12913 Would you be OK merging and deploying these sorts of changes in the future?

**Comment by yorinasub17** [comment]
Thanks! Merging this in, but will need help to deploy.

**Comment by eak12913** [comment]
I'll deploy this momentarily!

**Comment by eak12913** [comment]
This is now live. Apologies for the delay. Next time I will just merge and deploy something like this immediately.

**Pull request merged**
