### PR TITLE
Fix paragraph spacing in Guides

### PR DESCRIPTION
**Pull request by eak12913**
This quick PR addresses the overly tight (lack of) spacing between some paragraphs in our guides.  The way that the CSS is structured in this product leaves many ways in which inconsistency can be introduced. I'm not going to deal with the larger issues in this PR but will simply address the problem.

Before:
image

After:
image

### CODE REVIEW

**Comment by josh-padnick** [comment]
Reviewing this some 3 weeks later, but this looks good. Will approve now!

**Review by josh-padnick — APPROVED** [review]

**Comment by eak12913** [comment]
@oredavids: I somehow missed this PR. Josh approved it a week ago but he also updated the branch. Could you please approve this PR so that we could just merge it. Thank you!

**Review by infraredgirl — APPROVED** [review]
LGTM!

**Comment by eak12913** [comment]
Thanks @infraredgirl!

**Comment by eak12913** [comment]
Released!

**Pull request merged**
