### PR TITLE
Making Pro Serve job description more concise

### PR DESCRIPTION
**Pull request by pete0emerson**

### CODE REVIEW

**Review by zackproser — APPROVED** [review]
LGTM :+1:

**Review by brikis98 — APPROVED** [review]
LGTM!

**Comment by brikis98** [comment]
Shared on social media to get another round of feedback.

**Comment by brikis98** [comment]
Social media post is here: https://twitter.com/brikis98/status/1470800853887950848

Early feedback seems positive, but suggests there may be a small typo.

**Comment by pete0emerson** [comment]
New PR for typo: https://github.com/gruntwork-io/gruntwork-io.github.io/pull/674

**Pull request merged**
